### ISSUE TITLE
Modified instructional duties (not parental leave)

### ISSUE THREAD

**Issue by jameshowison** [aaronclauset/parental-leave#1]
Just perhaps of interest, some universities have a policy that makes parenting (and other care-giving) easier, by making work more flexible, although it stops short of providing paid leave:

https://policies.utexas.edu/policies/modified-instructional-duties

**Comment by dblarremore** [comment]
Thanks James. We'll add this to the notes column in the spreadsheet!

**Comment by samfway** [comment]
Added a note about this (9fdcb537a09ea02e6cebca7ac7cb1b1387e34600) to UT Austin's record. Thank you, James!
